version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "14:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 99
  labels:
  - "category: dependencies"
 
